### ISSUE TITLE
Android 7.0,API 24,横屏时无法播放视频

### ISSUE THREAD

**Issue by Lxinyuelxy** [linsea/UniversalVideoView#26]

**Comment by linsea** [comment]
你是运行里面的Demo还是你自己的项目而无法播放视频? 有什么现象吗?

**Comment by Lxinyuelxy** [comment]
你好,我是自己新建的一个Demo
![截图](http://ofsip1pyr.bkt.clouddn.com/Screenshot_20170424-201400.png)
![截图](http://ofsip1pyr.bkt.clouddn.com/Screenshot_20170424-201408.png)

**Comment by linsea** [comment]
你是否加入访问网络的权限? 可否把代码贴出来看看?

**Comment by Lxinyuelxy** [comment]
你好，我是直接把universalviewsample中MainActivity和布局文件中的代码贴在新建的Demo中，相应权限也加了。

**Comment by linsea** [comment]
那7.0以下的版本横屏有问题吗?

**Comment by Lxinyuelxy** [comment]
`
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
`
`
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
`
`
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
`
`
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
`


`
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.IllegalStateException: Binder has been finalized!
              at android.os.BinderProxy.transactNative(Native Method)
              at android.os.BinderProxy.transact(Binder.java:628)
              at com.android.internal.app.IAppOpsService$Stub$Proxy.stopWatchingMode(IAppOpsService.java:435)
              at android.media.PlayerBase.baseRelease(PlayerBase.java:136)
              at android.media.MediaPlayer.finalize(MediaPlayer.java:3721)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
              at java.lang.Thread.run(Thread.java:761)
`
型号是三星盖乐世.
用API22的模拟器横屏可以播放.

**Comment by linsea** [comment]
我在7.0的官方模拟器上跑universalviewsample横屏没有问题，你仔细对比下你自己的DEMO与universalviewsample项目的所有文件，看是否哪儿不对了。

**Comment by Lxinyuelxy** [comment]
好的,那我再看看,谢谢了.
